### PR TITLE
Setup automatic changelog

### PR DESCRIPTION
**Pull request by GreatWizard**
This PR has to be merged after #112

### CODE REVIEW

**Comment by xcambar** [comment]
Testa are broken, probably because of https://circleci.com/gh/novafloss/formidable-core/274

**Comment by GreatWizard** [comment]
I don't know, it's difficult to trust circleci :/

**Comment by GreatWizard** [comment]
There are connection errors, weird things and when you rebuild without cache it's fine... :(

**Comment by GreatWizard** [comment]
Travis says YES. It's fine for me.

**Pull request merged**
